width, height = 1600, 900  # размеры окна
FPS = 60
cell_bact = 20  # размер бактерии
cell_food = 8  # размер еды
life_bacts = 70  # изначальная энергия бактерии
color_bact_herb = "#4b86e7" # цвет бактерии
color_bact_omn = "orange"
qu_food = 450  # количетсво еды на поле
spawn_food = 1000 # скорость спавна еды в мс
title = 'Бактерии'  # название программы
